# Generated by Django 2.0 on 2019-04-29 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 4, 29, 8, 32, 34, 676772)),
        ),
    ]
